package com.com.redhat.demo.dmn.car_insurance_quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Car() {
    }




}